#! /bin/bash
# SPDX-License-Identifier: MIT
#
# #######################################
# # WARNING, arkify is still early WIP! #
# #######################################
#
# #######################################
#
# Poor man's TODO list:
#
# - Add a hook to the ark-infra to check if ark-infra needs to be updated in case
#   the user updated or rebased the branch?
# - Better error handling, including collision detection for the names chosen for
#   the remotes and branches we create.
# - Support RHEL/CentOS et. al.
# - Fix all FIXME in the code; this includes:
#   * When updating afk-infra-local-* branches, whenever possible use a merge
#     instead of rebase.
#   * Check if any patches in ark-fixes- branches already have been applied.
#
# #######################################


_afy_perform_startup()
{
	set -e

	_afy_target_branch=$(git rev-parse --abbrev-ref HEAD)

	# check Fedora
	if ! [[ -e /etc/os-release ]] || ! grep -i 'ID.*fedora' /etc/os-release &> /dev/null; then
		echo "Aborting, arkify only supports Fedora Linux and its derivatives, including RHEL and CentOS." >&2
		exit 1
	fi

	# check repo for uncommitted changes
	if ! LC_ALL=C git status 2>/dev/null | grep '^nothing to commit, working tree clean' &> /dev/null; then
		echo "Aborting: uncommitted changes or untracked files present." >&2
		exit 1
	fi

	# check if we are in a branch that makes no sense to arkify
	if [[ "${_afy_target_branch}" != "${_afy_target_branch#arkify-}" ]]; then
		echo "Aborting, looks like you are in a arkify-* branch, this is unlikely what you want."
		exit 1
	fi

	# check git & kernel
	if [[ ! -d '.git' ]] || [[ $(head -n 1 'README' 2> /dev/null) != 'Linux kernel' ]]; then
		echo "Aborting: this does not look like Git repository with the Linux sources."
		exit 1
	fi

	# check required packages
	local missing_pkgs=''
	# following list taken from https://cki-project.gitlab.io/kernel-ark/
	for pkg in git make gcc flex bison bzip2 rpm-build python3-pyyaml; do
		if ! rpm -q "${pkg}" &> /dev/null; then
			missing_pkgs+=" ${pkg}"
		fi
	done
	if [[ "${missing_pkgs}" ]]; then
		echo "Aborting, please install the following packages'${missing_pkgs}'."
		exit
	fi


	# parse parameters
	for parameter in $@; do
		case "${parameter}" in
		--latest|--rawhide) _afy_arkinfra_rawhide="True" ;;
		*)
			echo "Aborting, parameter '${parameter}' unkown."
			exit 1
			;;
		esac
	done

	if [[ "${_afy_arkinfra_rawhide}" ]]; then
		_afy_target_kind=mainline
	else
		if [[ -e "$(git rev-parse --show-toplevel)/Next/SHA1s" ]]; then
			_afy_target_kind=next
		elif grep -e '^SUBLEVEL = [1-9]' "$(git rev-parse --show-toplevel)"/Makefile &> /dev/null; then
			_afy_target_kind="$(make -s kernelversion)"
			_afy_target_kind="stable-${_afy_target_kind%.*}"
		else
			_afy_target_kind=mainline
		fi

		if ! [[ "$(git ls-remote --heads https://gitlab.com/knurd42/linux.git/ refs/heads/arkify-infra-"${_afy_target_kind}")" ]]; then
			echo "WARNING: suitable remote not found; using mainline"
			_afy_target_kind=mainline
		fi
	fi
}


_afy_ensure_remote_present()
{
	if ! git remote -v | grep -e '^arkify[[:blank:]]*https://gitlab.com/knurd42/linux.git/' &> /dev/null; then
		echo "* Adding remote 'arkify'".
		git remote add -t arkify-arkify arkify https://gitlab.com/knurd42/linux.git/
	fi
	local remote_branches
	remote_branches="$(git branch --list -r 'arkify*')"
	local branches_interested_in=(arkify-fixes-"${_afy_target_kind}" arkify-infra-"${_afy_target_kind}" arkify-upstream-"${_afy_target_kind}")
	if [[ "${_afy_target_kind}" =~ (mainline|next) ]]; then
		branches_interested_in+=(arkify-infra-"${_afy_target_kind}"-latest)
	fi
	for branch in "${branches_interested_in[@]}"; do
		if ! echo "${remote_branches}" | grep -E "^[[:blank:]] arkify/${branch}$" &> /dev/null; then
			echo "* Adding remote branch 'arkify/${branch}'"
			git remote set-branches --add arkify "${branch}"
		fi
	done
}


_afy_fetch_arkify()
{
	echo "* Fetching remote 'arkify'".
	git fetch --quiet arkify
}


_afy_handle_arkify-upstream-branch()
{
	# create a branch the ark-infra requires to separate upstream from downstream.
	local merge_base
	merge_base="$(git merge-base "${_afy_target_branch}" arkify/arkify-upstream-"${_afy_target_kind}")"
	if ! git branch -l | grep "^[[:blank:]]*arkify-local-upstream-${_afy_target_branch}" &> /dev/null; then
		echo "* Creating branch 'arkify-local-upstream-${_afy_target_branch}' based on '$(git describe "${merge_base}")'."
		git branch --quiet "arkify-local-upstream-${_afy_target_branch}" "${merge_base}"
		return
	fi

	local current_head
	current_head="$(git rev-parse arkify-local-upstream-"${_afy_target_branch}")"
	if  ! [[ "${current_head}" == "${merge_base}" ]]; then
		echo "* Force updating 'arkify-local-upstream-${_afy_target_branch}' to '$(git describe "${merge_base}")' (was: '${current_head:0:14}'."
		git branch --force --quiet "arkify-local-upstream-${_afy_target_branch}" "${merge_base}"
	fi
}


_afy_handle_arkify-infra-branch()
{
	local date_upstream_branch
	date_upstream_branch="$(git show -s --format=%ct arkify-local-upstream-"${_afy_target_branch}")"

	local _arkify_tagnames_tolookfor="arkify-infra-${_afy_target_kind}"
	if [[ "${_afy_target_kind}" =~ (mainline|next) ]]; then
		_arkify_tagnames_tolookfor+="-latest"
	fi
	if [[ ! "${_afy_arkinfra_rawhide}" ]]; then
		while read -r arkify_tagname tagdate; do
			if (( tagdate > date_upstream_branch )); then
				break;
			fi
		done < <(git tag --sort=creatordate --format '%(refname:strip=2) %(creatordate:unix)' -l "${_arkify_tagnames_tolookfor}"-2\*)
	fi

	# fallback: try latest in case no tag was found or if _afy_arkinfra_rawhide is set
	if [[ ! "${arkify_tagname}" ]]; then
		arkify_tagname=arkify/arkify-infra-"${_afy_target_kind}"
		if [[ "${_afy_target_kind}" =~ (mainline|next) ]]; then
			arkify_tagname+="-latest"
		fi
	fi

	# create or update a branch with the ark-infra to allow local changes
	if ! git branch -l | grep "^[[:blank:]]*arkify-local-infra-${_afy_target_branch}" &> /dev/null; then
		echo "* Creating branch 'arkify-local-infra-${_afy_target_branch}' based on '${arkify_tagname}'."
		git branch --quiet arkify-local-infra-"${_afy_target_branch}" "${arkify_tagname}"

		echo "* Checking out branch 'arkify-local-infra-${_afy_target_branch}'."
		git checkout --quiet arkify-local-infra-"${_afy_target_branch}"

		echo "* Adjusting ark-infra configuration in 'redhat/Makefile.variables'."
		echo $'\n'"DISTLOCALVERSION ?= .$(whoami)" >> redhat/Makefile.variables
		# FIXME: this hardcodes a few things which might be a bad idea:
		# - BUMP_RELEASE (might not be a good idea for this usecase)
		# - VERSION_ON_UPSTREAM=1 (wrong for stable)
		sed -i '
			s!^\(PATCHLIST_URL \?.\?=\)\(.*\)!\1 none! ;
			s!^\(RELEASED_KERNEL \?.\?=\)\(.*\)!\11! ;
			s!\(VERSION_ON_UPSTREAM \?.\?=\)\(.*\)!\1 1! ;
		       ' redhat/Makefile.variables
		git commit --quiet -s -m 'local ark-infra configuration' redhat/Makefile.variables
	elif git merge-base --is-ancestor "${arkify_tagname}" arkify-local-infra-"${_afy_target_branch}"; then
		echo "* Branch 'arkify-local-infra-${_afy_target_branch}' is up to date with '${arkify_tagname}'."
	else
		# FIXME: whenever possible, use a merge instead of rebase here:
		if [[ "$(git rev-parse --abbrev-ref HEAD)" != arkify-local-infra-"${_afy_target_branch}" ]]; then
			echo "* Checking out 'arkify-local-infra-${_afy_target_branch}'."
			git checkout --quiet arkify-local-infra-"${_afy_target_branch}"
		fi
		echo "* Rebasing 'arkify-local-infra-${_afy_target_branch}' ontop of ${arkify_tagname}."
		local _previous_base
		_previous_base="$(git tag --sort=-creatordate --merged arkify-local-infra-"${_afy_target_branch}" arkify-infra-\* | head -n 1)"
		git rebase --quiet --onto "${arkify_tagname}" "${_previous_base}"
	fi
}


_afy_import_arkify-infra()
{
	if [[ "$(git rev-parse --abbrev-ref HEAD)" != "${_afy_target_branch}" ]]; then
		echo "* Checking out '${_afy_target_branch}'."
		git checkout --quiet "${_afy_target_branch}"
	fi

	rm -rf makefile Makefile.rhelver redhat/
	# note: omitting Kconfig.redhat here and in related commands on purpose:
	git archive --format=tar arkify-local-infra-"${_afy_target_branch}" makefile Makefile.rhelver redhat/ .copr | tar -x
	sed -i '
		s!^\(UPSTREAM_BRANCH \?.\?=\)\(.*\)!\1 '"arkify-local-upstream-${_afy_target_branch}"'! ;
	       ' redhat/Makefile.variables
	# FIXME: is this actually needed?
	if ! grep -E '^include Makefile.rhelver$' Makefile &>/dev/null; then
		sed -i '/# We are using a recursive / i include Makefile.rhelver\n' Makefile
	fi
	git add makefile Makefile.rhelver Makefile redhat
	git add -f .copr
	if ! git diff --cached --exit-code &> /dev/null; then
		echo "* Importing ark infrastructure from 'arkify-local-infra-${_afy_target_branch}'."
		git commit --quiet -s -m "bulk import ark-infra"
	else
		echo "* Ark infrastructure in '${_afy_target_branch}' up to date with 'arkify-local-infra-${_afy_target_branch}'."
	fi
}

_afy_check_fixes()
{
	local date_upstream_branch
	date_upstream_branch="$(git show -s --format=%ct arkify-local-upstream-"${_afy_target_branch}")"

	if [[ "${_afy_arkinfra_rawhide}" ]]; then
		# you are own your own here
		return 0
	fi

	while read -r arkify_fixes_tagname tagdate; do
		if (( tagdate >= date_upstream_branch )); then
			break;
		fi
	done < <(git tag --sort=creatordate --format '%(refname:strip=2) %(creatordate:unix)' -l "arkify-fixes-${_afy_target_kind}"-2\*)
	# fallback: try latest in case no tag was found
	if [[ ! "${arkify_fixes_tagname}" ]]; then
		if [[ "$(git branch -rl arkify/arkify-fixes-"${_afy_target_kind}")" ]]; then
			arkify_fixes_tagname=arkify/arkify-fixes-"${_afy_target_kind}"
		else
			echo $'\n'"[ Note, was unable to check if fixes might be required. ]"
			return 0
		fi
	fi

	local fixes_merge_base
	merge_base="$(git merge-base arkify/arkify-upstream-"${_afy_target_kind}" "${arkify_fixes_tagname}")"

	local _fixes
	_fixes="$(git log --oneline --no-merges "${merge_base}".."${arkify_fixes_tagname}")"
	# FIXME: do not warn if the patches have been applied already.
	if [[ "${_fixes}" ]]; then
		echo
		echo "$(tput setab 1) WARNING: $(tput sgr0)You depending on your kernel and spec file configuration might need to cherry-pick the following fixes into you '${_afy_target_branch}' branch for the build to succeed:"
		echo "${_fixes}"
		echo
		sleep 2
	fi
}


# define three variables that _afy_perform_startup will set
_afy_target_branch=''
_afy_target_kind=''
_afy_arkinfra_rawhide=''
_afy_perform_startup "$@"

# go
_afy_ensure_remote_present
_afy_fetch_arkify
_afy_handle_arkify-upstream-branch
_afy_handle_arkify-infra-branch
_afy_import_arkify-infra

# finish
echo $'\n'"Done; now run 'make dist-srpm' and then use something like"
echo "'mock redhat/rpm/SRPMS/kernel-*.src.rpm' to build the SRPM."
_afy_check_fixes
