/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (C) 2014-2020 NXP Semiconductors, All Rights Reserved.
 * Copyright 2021 GOODIX
 */


/** Filename: Tfa98xx_TfaFieldnames.h
 *	This file was generated automatically on 09/01/15 at 09:40:28.
 *	Source file: TFA9888_N1C_I2C_regmap_V1.xlsx
 */
#define TFA9888_I2CVERSION 18
enum Tfa2BfEnumList {
	TFA2_BF_PWDN	= 0x0000,	/*!< Powerdown selection			                     */
	TFA2_BF_I2CR	= 0x0010,	/*!< I2C Reset - Auto clear			                  */
	TFA2_BF_CFE	= 0x0020,	/*!< Enable CoolFlux			                          */
	TFA2_BF_AMPE	= 0x0030,	/*!< Activate Amplifier			                      */
	TFA2_BF_DCA	= 0x0040,	/*!< Activate DC-to-DC converter			              */
	TFA2_BF_SBSL	= 0x0050,	/*!< Coolflux configured			                     */
	TFA2_BF_AMPC	= 0x0060,	/*!< CoolFlux controls amplifier			             */
	TFA2_BF_INTP	= 0x0071,	/*!< Interrupt config			                        */
	TFA2_BF_FSSSEL= 0x0091,	/*!< Audio sample reference				                */
	TFA2_BF_BYPOCP= 0x00b0,	/*!< Bypass OCP				                            */
	TFA2_BF_TSTOCP= 0x00c0,	/*!< OCP testing control				                   */
	TFA2_BF_AMPINSEL= 0x0101,	/*!< Amplifier input selection				             */
	TFA2_BF_MANSCONF= 0x0120,	/*!< I2C configured				                        */
	TFA2_BF_MANCOLD= 0x0130,	/*!< Execute cold start				                    */
	TFA2_BF_MANAOOSC= 0x0140,	/*!< Internal osc off at PWDN				              */
	TFA2_BF_MANROBOD= 0x0150,	/*!< Reaction on BOD				                       */
	TFA2_BF_BODE	= 0x0160,	/*!< BOD Enable			                              */
	TFA2_BF_BODHYS= 0x0170,	/*!< BOD Hysteresis				                        */
	TFA2_BF_BODFILT= 0x0181,	/*!< BOD filter				                            */
	TFA2_BF_BODTHLVL= 0x01a1,	/*!< BOD threshold				                         */
	TFA2_BF_MUTETO= 0x01d0,	/*!< Time out SB mute sequence				             */
	TFA2_BF_RCVNS = 0x01e0,	/*!< Noise shaper selection				                */
	TFA2_BF_MANWDE= 0x01f0,	/*!< Watchdog manager reaction				             */
	TFA2_BF_AUDFS = 0x0203,	/*!< Sample rate (fs)				                      */
	TFA2_BF_INPLEV= 0x0240,	/*!< TDM output attenuation				                */
	TFA2_BF_FRACTDEL= 0x0255,	/*!< V/I Fractional delay				                  */
	TFA2_BF_BYPHVBF= 0x02b0,	/*!< Bypass HVBAT filter				                   */
	TFA2_BF_LDOBYP= 0x02c0,	/*!< Receiver LDO bypass				                   */
	TFA2_BF_REV	= 0x030f,	/*!< Revision info			                            */
	TFA2_BF_REFCKEXT= 0x0401,	/*!< PLL external ref clock				                */
	TFA2_BF_REFCKSEL= 0x0420,	/*!< PLL internal ref clock				                */
	TFA2_BF_SSLEFTE= 0x0500,	/*!< Enable left channel				                   */
	TFA2_BF_SSRIGHTE= 0x0510,	/*!< Enable right channel				                  */
	TFA2_BF_VSLEFTE= 0x0520,	/*!< Voltage sense left				                    */
	TFA2_BF_VSRIGHTE= 0x0530,	/*!< Voltage sense right				                   */
	TFA2_BF_CSLEFTE= 0x0540,	/*!< Current sense left				                    */
	TFA2_BF_CSRIGHTE= 0x0550,	/*!< Current sense right				                   */
	TFA2_BF_SSPDME= 0x0560,	/*!< Sub-system PDM				                        */
	TFA2_BF_STGAIN= 0x0d18,	/*!< Side tone gain				                        */
	TFA2_BF_PDMSMUTE= 0x0da0,	/*!< Side tone soft mute				                   */
	TFA2_BF_SWVSTEP= 0x0e06,	/*!< Register for the host SW to record the current active vstep */
	TFA2_BF_VDDS	= 0x1000,	/*!< POR			                                     */
	TFA2_BF_PLLS	= 0x1010,	/*!< PLL lock			                                */
	TFA2_BF_OTDS	= 0x1020,	/*!< OTP alarm			                               */
	TFA2_BF_OVDS	= 0x1030,	/*!< OVP alarm			                               */
	TFA2_BF_UVDS	= 0x1040,	/*!< UVP alarm			                               */
	TFA2_BF_CLKS	= 0x1050,	/*!< Clocks stable			                           */
	TFA2_BF_MTPB	= 0x1060,	/*!< MTP busy			                                */
	TFA2_BF_NOCLK = 0x1070,	/*!< Lost clock				                            */
	TFA2_BF_SPKS	= 0x1080,	/*!< Speaker error			                           */
	TFA2_BF_ACS	= 0x1090,	/*!< Cold Start			                               */
	TFA2_BF_SWS	= 0x10a0,	/*!< Amplifier engage			                         */
	TFA2_BF_WDS	= 0x10b0,	/*!< Watchdog			                                 */
	TFA2_BF_AMPS	= 0x10c0,	/*!< Amplifier enable			                        */
	TFA2_BF_AREFS = 0x10d0,	/*!< References enable				                     */
	TFA2_BF_ADCCR = 0x10e0,	/*!< Control ADC				                           */
	TFA2_BF_BODNOK= 0x10f0,	/*!< BOD				                                   */
	TFA2_BF_DCIL	= 0x1100,	/*!< DCDC current limiting			                   */
	TFA2_BF_DCDCA = 0x1110,	/*!< DCDC active				                           */
	TFA2_BF_DCOCPOK= 0x1120,	/*!< DCDC OCP nmos				                         */
	TFA2_BF_DCHVBAT= 0x1140,	/*!< DCDC level 1x				                         */
	TFA2_BF_DCH114= 0x1150,	/*!< DCDC level 1.14x				                      */
	TFA2_BF_DCH107= 0x1160,	/*!< DCDC level 1.07x				                      */
	TFA2_BF_STMUTEB= 0x1170,	/*!< side tone (un)mute busy				               */
	TFA2_BF_STMUTE= 0x1180,	/*!< side tone mute state				                  */
	TFA2_BF_TDMLUTER= 0x1190,	/*!< TDM LUT error				                         */
	TFA2_BF_TDMSTAT= 0x11a2,	/*!< TDM status bits				                       */
	TFA2_BF_TDMERR= 0x11d0,	/*!< TDM error				                             */
	TFA2_BF_HAPTIC= 0x11e0,	/*!< Status haptic driver				                  */
	TFA2_BF_OCPOAPL= 0x1200,	/*!< OCPOK pmos A left				                     */
	TFA2_BF_OCPOANL= 0x1210,	/*!< OCPOK nmos A left				                     */
	TFA2_BF_OCPOBPL= 0x1220,	/*!< OCPOK pmos B left				                     */
	TFA2_BF_OCPOBNL= 0x1230,	/*!< OCPOK nmos B left				                     */
	TFA2_BF_CLIPAHL= 0x1240,	/*!< Clipping A left to Vddp				               */
	TFA2_BF_CLIPALL= 0x1250,	/*!< Clipping A left to gnd				                */
	TFA2_BF_CLIPBHL= 0x1260,	/*!< Clipping B left to Vddp				               */
	TFA2_BF_CLIPBLL= 0x1270,	/*!< Clipping B left to gnd				                */
	TFA2_BF_OCPOAPRC= 0x1280,	/*!< OCPOK pmos A RCV				                      */
	TFA2_BF_OCPOANRC= 0x1290,	/*!< OCPOK nmos A RCV				                      */
	TFA2_BF_OCPOBPRC= 0x12a0,	/*!< OCPOK pmos B RCV				                      */
	TFA2_BF_OCPOBNRC= 0x12b0,	/*!< OCPOK nmos B RCV				                      */
	TFA2_BF_RCVLDOR= 0x12c0,	/*!< RCV LDO regulates				                     */
	TFA2_BF_RCVLDOBR= 0x12d0,	/*!< Receiver LDO ready				                    */
	TFA2_BF_OCDSL = 0x12e0,	/*!< OCP left amplifier				                    */
	TFA2_BF_CLIPSL= 0x12f0,	/*!< Amplifier left clipping				               */
	TFA2_BF_OCPOAPR= 0x1300,	/*!< OCPOK pmos A right				                    */
	TFA2_BF_OCPOANR= 0x1310,	/*!< OCPOK nmos A right				                    */
	TFA2_BF_OCPOBPR= 0x1320,	/*!< OCPOK pmos B right				                    */
	TFA2_BF_OCPOBNR= 0x1330,	/*!< OCPOK nmos B right				                    */
	TFA2_BF_CLIPAHR= 0x1340,	/*!< Clipping A right to Vddp				              */
	TFA2_BF_CLIPALR= 0x1350,	/*!< Clipping A right to gnd				               */
	TFA2_BF_CLIPBHR= 0x1360,	/*!< Clipping B left to Vddp				               */
	TFA2_BF_CLIPBLR= 0x1370,	/*!< Clipping B right to gnd				               */
	TFA2_BF_OCDSR = 0x1380,	/*!< OCP right amplifier				                   */
	TFA2_BF_CLIPSR= 0x1390,	/*!< Amplifier right clipping				              */
	TFA2_BF_OCPOKMC= 0x13a0,	/*!< OCPOK MICVDD				                          */
	TFA2_BF_MANALARM= 0x13b0,	/*!< Alarm state				                           */
	TFA2_BF_MANWAIT1= 0x13c0,	/*!< Wait HW I2C settings				                  */
	TFA2_BF_MANWAIT2= 0x13d0,	/*!< Wait CF config				                        */
	TFA2_BF_MANMUTE= 0x13e0,	/*!< Audio mute sequence				                   */
	TFA2_BF_MANOPER= 0x13f0,	/*!< Operating state				                       */
	TFA2_BF_SPKSL = 0x1400,	/*!< Left speaker status				                   */
	TFA2_BF_SPKSR = 0x1410,	/*!< Right speaker status				                  */
	TFA2_BF_CLKOOR= 0x1420,	/*!< External clock status				                 */
	TFA2_BF_MANSTATE= 0x1433,	/*!< Device manager status				                 */
	TFA2_BF_BATS	= 0x1509,	/*!< Battery voltage (V)			                     */
	TFA2_BF_TEMPS = 0x1608,	/*!< IC Temperature (C)				                    */
	TFA2_BF_TDMUC = 0x2003,	/*!< Usecase setting				                       */
	TFA2_BF_TDME	= 0x2040,	/*!< Enable interface			                        */
	TFA2_BF_TDMMODE= 0x2050,	/*!< Slave/master				                          */
	TFA2_BF_TDMCLINV= 0x2060,	/*!< Reception data to BCK clock				           */
	TFA2_BF_TDMFSLN= 0x2073,	/*!< FS length (master mode only)				          */
	TFA2_BF_TDMFSPOL= 0x20b0,	/*!< FS polarity				                           */
	TFA2_BF_TDMNBCK= 0x20c3,	/*!< N-BCK's in FS				                         */
	TFA2_BF_TDMSLOTS= 0x2103,	/*!< N-slots in Frame				                      */
	TFA2_BF_TDMSLLN= 0x2144,	/*!< N-bits in slot				                        */
	TFA2_BF_TDMBRMG= 0x2194,	/*!< N-bits remaining				                      */
	TFA2_BF_TDMDEL= 0x21e0,	/*!< data delay to FS				                      */
	TFA2_BF_TDMADJ= 0x21f0,	/*!< data adjustment				                       */
	TFA2_BF_TDMOOMP= 0x2201,	/*!< Received audio compression				            */
	TFA2_BF_TDMSSIZE= 0x2224,	/*!< Sample size per slot				                  */
	TFA2_BF_TDMTXDFO= 0x2271,	/*!< Format unused bits				                    */
	TFA2_BF_TDMTXUS0= 0x2291,	/*!< Format unused slots GAINIO				            */
	TFA2_BF_TDMTXUS1= 0x22b1,	/*!< Format unused slots DIO1				              */
	TFA2_BF_TDMTXUS2= 0x22d1,	/*!< Format unused slots DIO2				              */
	TFA2_BF_TDMLE = 0x2310,	/*!< Control audio left				                    */
	TFA2_BF_TDMRE = 0x2320,	/*!< Control audio right				                   */
	TFA2_BF_TDMVSRE= 0x2340,	/*!< Control voltage sense right				           */
	TFA2_BF_TDMCSRE= 0x2350,	/*!< Control current sense right				           */
	TFA2_BF_TDMVSLE= 0x2360,	/*!< Voltage sense left control				            */
	TFA2_BF_TDMCSLE= 0x2370,	/*!< Current sense left control				            */
	TFA2_BF_TDMCFRE= 0x2380,	/*!< DSP out right control				                 */
	TFA2_BF_TDMCFLE= 0x2390,	/*!< DSP out left control				                  */
	TFA2_BF_TDMCF3E= 0x23a0,	/*!< AEC ref left control				                  */
	TFA2_BF_TDMCF4E= 0x23b0,	/*!< AEC ref right control				                 */
	TFA2_BF_TDMPD1E= 0x23c0,	/*!< PDM 1 control				                         */
	TFA2_BF_TDMPD2E= 0x23d0,	/*!< PDM 2 control				                         */
	TFA2_BF_TDMLIO= 0x2421,	/*!< IO audio left				                         */
	TFA2_BF_TDMRIO= 0x2441,	/*!< IO audio right				                        */
	TFA2_BF_TDMVSRIO= 0x2481,	/*!< IO voltage sense right				                */
	TFA2_BF_TDMCSRIO= 0x24a1,	/*!< IO current sense right				                */
	TFA2_BF_TDMVSLIO= 0x24c1,	/*!< IO voltage sense left				                 */
	TFA2_BF_TDMCSLIO= 0x24e1,	/*!< IO current sense left				                 */
	TFA2_BF_TDMCFRIO= 0x2501,	/*!< IO dspout right				                       */
	TFA2_BF_TDMCFLIO= 0x2521,	/*!< IO dspout left				                        */
	TFA2_BF_TDMCF3IO= 0x2541,	/*!< IO AEC ref left control				               */
	TFA2_BF_TDMCF4IO= 0x2561,	/*!< IO AEC ref right control				              */
	TFA2_BF_TDMPD1IO= 0x2581,	/*!< IO pdm1				                               */
	TFA2_BF_TDMPD2IO= 0x25a1,	/*!< IO pdm2				                               */
	TFA2_BF_TDMLS = 0x2643,	/*!< Position audio left				                   */
	TFA2_BF_TDMRS = 0x2683,	/*!< Position audio right				                  */
	TFA2_BF_TDMVSRS= 0x2703,	/*!< Position voltage sense right				          */
	TFA2_BF_TDMCSRS= 0x2743,	/*!< Position current sense right				          */
	TFA2_BF_TDMVSLS= 0x2783,	/*!< Position voltage sense left				           */
	TFA2_BF_TDMCSLS= 0x27c3,	/*!< Position current sense left				           */
	TFA2_BF_TDMCFRS= 0x2803,	/*!< Position dspout right				                 */
	TFA2_BF_TDMCFLS= 0x2843,	/*!< Position dspout left				                  */
	TFA2_BF_TDMCF3S= 0x2883,	/*!< Position AEC ref left control				         */
	TFA2_BF_TDMCF4S= 0x28c3,	/*!< Position AEC ref right control				        */
	TFA2_BF_TDMPD1S= 0x2903,	/*!< Position pdm1				                         */
	TFA2_BF_TDMPD2S= 0x2943,	/*!< Position pdm2				                         */
	TFA2_BF_PDMSM = 0x3100,	/*!< PDM control				                           */
	TFA2_BF_PDMSTSEL= 0x3111,	/*!< Side tone input				                       */
	TFA2_BF_PDMLSEL= 0x3130,	/*!< PDM data selection for left channel during PDM direct mode */
	TFA2_BF_PDMRSEL= 0x3140,	/*!< PDM data selection for right channel during PDM direct mode */
	TFA2_BF_MICVDDE= 0x3150,	/*!< Enable MICVDD				                         */
	TFA2_BF_PDMCLRAT= 0x3201,	/*!< PDM BCK/Fs ratio				                      */
	TFA2_BF_PDMGAIN= 0x3223,	/*!< PDM gain				                              */
	TFA2_BF_PDMOSEL= 0x3263,	/*!< PDM output selection - RE/FE data combination		*/
	TFA2_BF_SELCFHAPD= 0x32a0,	/*!< Select the source for haptic data output (not for customer) */
	TFA2_BF_HAPTIME= 0x3307,	/*!< Duration (ms)				                         */
	TFA2_BF_HAPLEVEL= 0x3387,	/*!< DC value (FFS)				                        */
	TFA2_BF_GPIODIN= 0x3403,	/*!< Receiving value				                       */
	TFA2_BF_GPIOCTRL= 0x3500,	/*!< GPIO master control over GPIO1/2 ports (not for customer) */
	TFA2_BF_GPIOCONF= 0x3513,	/*!< Configuration				                         */
	TFA2_BF_GPIODOUT= 0x3553,	/*!< Transmitting value				                    */
	TFA2_BF_ISTVDDS= 0x4000,	/*!< Status POR				                            */
	TFA2_BF_ISTPLLS= 0x4010,	/*!< Status PLL lock				                       */
	TFA2_BF_ISTOTDS= 0x4020,	/*!< Status OTP alarm				                      */
	TFA2_BF_ISTOVDS= 0x4030,	/*!< Status OVP alarm				                      */
	TFA2_BF_ISTUVDS= 0x4040,	/*!< Status UVP alarm				                      */
	TFA2_BF_ISTCLKS= 0x4050,	/*!< Status clocks stable				                  */
	TFA2_BF_ISTMTPB= 0x4060,	/*!< Status MTP busy				                       */
	TFA2_BF_ISTNOCLK= 0x4070,	/*!< Status lost clock				                     */
	TFA2_BF_ISTSPKS= 0x4080,	/*!< Status speaker error				                  */
	TFA2_BF_ISTACS= 0x4090,	/*!< Status cold start				                     */
	TFA2_BF_ISTSWS= 0x40a0,	/*!< Status amplifier engage				               */
	TFA2_BF_ISTWDS= 0x40b0,	/*!< Status watchdog				                       */
	TFA2_BF_ISTAMPS= 0x40c0,	/*!< Status amplifier enable				               */
	TFA2_BF_ISTAREFS= 0x40d0,	/*!< Status Ref enable				                     */
	TFA2_BF_ISTADCCR= 0x40e0,	/*!< Status Control ADC				                    */
	TFA2_BF_ISTBODNOK= 0x40f0,	/*!< Status BOD				                            */
	TFA2_BF_ISTBSTCU= 0x4100,	/*!< Status DCDC current limiting				          */
	TFA2_BF_ISTBSTHI= 0x4110,	/*!< Status DCDC active				                    */
	TFA2_BF_ISTBSTOC= 0x4120,	/*!< Status DCDC OCP				                       */
	TFA2_BF_ISTBSTPKCUR= 0x4130,	/*!< Status bst peakcur				                    */
	TFA2_BF_ISTBSTVC= 0x4140,	/*!< Status DCDC level 1x				                  */
	TFA2_BF_ISTBST86= 0x4150,	/*!< Status DCDC level 1.14x				               */
	TFA2_BF_ISTBST93= 0x4160,	/*!< Status DCDC level 1.07x				               */
	TFA2_BF_ISTRCVLD= 0x4170,	/*!< Status rcvldop ready				                  */
	TFA2_BF_ISTOCPL= 0x4180,	/*!< Status ocp alarm left				                 */
	TFA2_BF_ISTOCPR= 0x4190,	/*!< Status ocp alarm right				                */
	TFA2_BF_ISTMWSRC= 0x41a0,	/*!< Status Waits HW I2C settings				          */
	TFA2_BF_ISTMWCFC= 0x41b0,	/*!< Status waits CF config				                */
	TFA2_BF_ISTMWSMU= 0x41c0,	/*!< Status Audio mute sequence				            */
	TFA2_BF_ISTCFMER= 0x41d0,	/*!< Status cfma error				                     */
	TFA2_BF_ISTCFMAC= 0x41e0,	/*!< Status cfma ack				                       */
	TFA2_BF_ISTCLKOOR= 0x41f0,	/*!< Status flag_clk_out_of_range				          */
	TFA2_BF_ISTTDMER= 0x4200,	/*!< Status tdm error				                      */
	TFA2_BF_ISTCLPL= 0x4210,	/*!< Status clip left				                      */
	TFA2_BF_ISTCLPR= 0x4220,	/*!< Status clip right				                     */
	TFA2_BF_ISTOCPM= 0x4230,	/*!< Status mic ocpok				                      */
	TFA2_BF_ICLVDDS= 0x4400,	/*!< Clear POR				                             */
	TFA2_BF_ICLPLLS= 0x4410,	/*!< Clear PLL lock				                        */
	TFA2_BF_ICLOTDS= 0x4420,	/*!< Clear OTP alarm				                       */
	TFA2_BF_ICLOVDS= 0x4430,	/*!< Clear OVP alarm				                       */
	TFA2_BF_ICLUVDS= 0x4440,	/*!< Clear UVP alarm				                       */
	TFA2_BF_ICLCLKS= 0x4450,	/*!< Clear clocks stable				                   */
	TFA2_BF_ICLMTPB= 0x4460,	/*!< Clear mtp busy				                        */
	TFA2_BF_ICLNOCLK= 0x4470,	/*!< Clear lost clk				                        */
	TFA2_BF_ICLSPKS= 0x4480,	/*!< Clear speaker error				                   */
	TFA2_BF_ICLACS= 0x4490,	/*!< Clear cold started				                    */
	TFA2_BF_ICLSWS= 0x44a0,	/*!< Clear amplifier engage				                */
	TFA2_BF_ICLWDS= 0x44b0,	/*!< Clear watchdog				                        */
	TFA2_BF_ICLAMPS= 0x44c0,	/*!< Clear enbl amp				                        */
	TFA2_BF_ICLAREFS= 0x44d0,	/*!< Clear ref enable				                      */
	TFA2_BF_ICLADCCR= 0x44e0,	/*!< Clear control ADC				                     */
	TFA2_BF_ICLBODNOK= 0x44f0,	/*!< Clear BOD				                             */
	TFA2_BF_ICLBSTCU= 0x4500,	/*!< Clear DCDC current limiting				           */
	TFA2_BF_ICLBSTHI= 0x4510,	/*!< Clear DCDC active				                     */
	TFA2_BF_ICLBSTOC= 0x4520,	/*!< Clear DCDC OCP				                        */
	TFA2_BF_ICLBSTPC= 0x4530,	/*!< Clear bst peakcur				                     */
	TFA2_BF_ICLBSTVC= 0x4540,	/*!< Clear DCDC level 1x				                   */
	TFA2_BF_ICLBST86= 0x4550,	/*!< Clear DCDC level 1.14x				                */
	TFA2_BF_ICLBST93= 0x4560,	/*!< Clear DCDC level 1.07x				                */
	TFA2_BF_ICLRCVLD= 0x4570,	/*!< Clear rcvldop ready				                   */
	TFA2_BF_ICLOCPL= 0x4580,	/*!< Clear ocp alarm left				                  */
	TFA2_BF_ICLOCPR= 0x4590,	/*!< Clear ocp alarm right				                 */
	TFA2_BF_ICLMWSRC= 0x45a0,	/*!< Clear wait HW I2C settings				            */
	TFA2_BF_ICLMWCFC= 0x45b0,	/*!< Clear wait cf config				                  */
	TFA2_BF_ICLMWSMU= 0x45c0,	/*!< Clear audio mute sequence				             */
	TFA2_BF_ICLCFMER= 0x45d0,	/*!< Clear cfma err				                        */
	TFA2_BF_ICLCFMAC= 0x45e0,	/*!< Clear cfma ack				                        */
	TFA2_BF_ICLCLKOOR= 0x45f0,	/*!< Clear flag_clk_out_of_range				           */
	TFA2_BF_ICLTDMER= 0x4600,	/*!< Clear tdm error				                       */
	TFA2_BF_ICLCLPL= 0x4610,	/*!< Clear clip left				                       */
	TFA2_BF_ICLCLPR= 0x4620,	/*!< Clear clip right				                      */
	TFA2_BF_ICLOCPM= 0x4630,	/*!< Clear mic ocpok				                       */
	TFA2_BF_IEVDDS= 0x4800,	/*!< Enable por				                            */
	TFA2_BF_IEPLLS= 0x4810,	/*!< Enable pll lock				                       */
	TFA2_BF_IEOTDS= 0x4820,	/*!< Enable OTP alarm				                      */
	TFA2_BF_IEOVDS= 0x4830,	/*!< Enable OVP alarm				                      */
	TFA2_BF_IEUVDS= 0x4840,	/*!< Enable UVP alarm				                      */
	TFA2_BF_IECLKS= 0x4850,	/*!< Enable clocks stable				                  */
	TFA2_BF_IEMTPB= 0x4860,	/*!< Enable mtp busy				                       */
	TFA2_BF_IENOCLK= 0x4870,	/*!< Enable lost clk				                       */
	TFA2_BF_IESPKS= 0x4880,	/*!< Enable speaker error				                  */
	TFA2_BF_IEACS = 0x4890,	/*!< Enable cold started				                   */
	TFA2_BF_IESWS = 0x48a0,	/*!< Enable amplifier engage				               */
	TFA2_BF_IEWDS = 0x48b0,	/*!< Enable watchdog				                       */
	TFA2_BF_IEAMPS= 0x48c0,	/*!< Enable enbl amp				                       */
	TFA2_BF_IEAREFS= 0x48d0,	/*!< Enable ref enable				                     */
	TFA2_BF_IEADCCR= 0x48e0,	/*!< Enable Control ADC				                    */
	TFA2_BF_IEBODNOK= 0x48f0,	/*!< Enable BOD				                            */
	TFA2_BF_IEBSTCU= 0x4900,	/*!< Enable DCDC current limiting				          */
	TFA2_BF_IEBSTHI= 0x4910,	/*!< Enable DCDC active				                    */
	TFA2_BF_IEBSTOC= 0x4920,	/*!< Enable DCDC OCP				                       */
	TFA2_BF_IEBSTPC= 0x4930,	/*!< Enable bst peakcur				                    */
	TFA2_BF_IEBSTVC= 0x4940,	/*!< Enable DCDC level 1x				                  */
	TFA2_BF_IEBST86= 0x4950,	/*!< Enable DCDC level 1.14x				               */
	TFA2_BF_IEBST93= 0x4960,	/*!< Enable DCDC level 1.07x				               */
	TFA2_BF_IERCVLD= 0x4970,	/*!< Enable rcvldop ready				                  */
	TFA2_BF_IEOCPL= 0x4980,	/*!< Enable ocp alarm left				                 */
	TFA2_BF_IEOCPR= 0x4990,	/*!< Enable ocp alarm right				                */
	TFA2_BF_IEMWSRC= 0x49a0,	/*!< Enable waits HW I2C settings				          */
	TFA2_BF_IEMWCFC= 0x49b0,	/*!< Enable man wait cf config				             */
	TFA2_BF_IEMWSMU= 0x49c0,	/*!< Enable man Audio mute sequence				        */
	TFA2_BF_IECFMER= 0x49d0,	/*!< Enable cfma err				                       */
	TFA2_BF_IECFMAC= 0x49e0,	/*!< Enable cfma ack				                       */
	TFA2_BF_IECLKOOR= 0x49f0,	/*!< Enable flag_clk_out_of_range				          */
	TFA2_BF_IETDMER= 0x4a00,	/*!< Enable tdm error				                      */
	TFA2_BF_IECLPL= 0x4a10,	/*!< Enable clip left				                      */
	TFA2_BF_IECLPR= 0x4a20,	/*!< Enable clip right				                     */
	TFA2_BF_IEOCPM1= 0x4a30,	/*!< Enable mic ocpok				                      */
	TFA2_BF_IPOVDDS= 0x4c00,	/*!< Polarity por				                          */
	TFA2_BF_IPOPLLS= 0x4c10,	/*!< Polarity pll lock				                     */
	TFA2_BF_IPOOTDS= 0x4c20,	/*!< Polarity OTP alarm				                    */
	TFA2_BF_IPOOVDS= 0x4c30,	/*!< Polarity OVP alarm				                    */
	TFA2_BF_IPOUVDS= 0x4c40,	/*!< Polarity UVP alarm				                    */
	TFA2_BF_IPOCLKS= 0x4c50,	/*!< Polarity clocks stable				                */
	TFA2_BF_IPOMTPB= 0x4c60,	/*!< Polarity mtp busy				                     */
	TFA2_BF_IPONOCLK= 0x4c70,	/*!< Polarity lost clk				                     */
	TFA2_BF_IPOSPKS= 0x4c80,	/*!< Polarity speaker error				                */
	TFA2_BF_IPOACS= 0x4c90,	/*!< Polarity cold started				                 */
	TFA2_BF_IPOSWS= 0x4ca0,	/*!< Polarity amplifier engage				             */
	TFA2_BF_IPOWDS= 0x4cb0,	/*!< Polarity watchdog				                     */
	TFA2_BF_IPOAMPS= 0x4cc0,	/*!< Polarity enbl amp				                     */
	TFA2_BF_IPOAREFS= 0x4cd0,	/*!< Polarity ref enable				                   */
	TFA2_BF_IPOADCCR= 0x4ce0,	/*!< Polarity Control ADC				                  */
	TFA2_BF_IPOBODNOK= 0x4cf0,	/*!< Polarity BOD				                          */
	TFA2_BF_IPOBSTCU= 0x4d00,	/*!< Polarity DCDC current limiting				        */
	TFA2_BF_IPOBSTHI= 0x4d10,	/*!< Polarity DCDC active				                  */
	TFA2_BF_IPOBSTOC= 0x4d20,	/*!< Polarity DCDC OCP				                     */
	TFA2_BF_IPOBSTPC= 0x4d30,	/*!< Polarity bst peakcur				                  */
	TFA2_BF_IPOBSTVC= 0x4d40,	/*!< Polarity DCDC level 1x				                */
	TFA2_BF_IPOBST86= 0x4d50,	/*!< Polarity DCDC level 1.14x				             */
	TFA2_BF_IPOBST93= 0x4d60,	/*!< Polarity DCDC level 1.07x				             */
	TFA2_BF_IPORCVLD= 0x4d70,	/*!< Polarity rcvldop ready				                */
	TFA2_BF_IPOOCPL= 0x4d80,	/*!< Polarity ocp alarm left				               */
	TFA2_BF_IPOOCPR= 0x4d90,	/*!< Polarity ocp alarm right				              */
	TFA2_BF_IPOMWSRC= 0x4da0,	/*!< Polarity waits HW I2C settings				        */
	TFA2_BF_IPOMWCFC= 0x4db0,	/*!< Polarity man wait cf config				           */
	TFA2_BF_IPOMWSMU= 0x4dc0,	/*!< Polarity man audio mute sequence				      */
	TFA2_BF_IPOCFMER= 0x4dd0,	/*!< Polarity cfma err				                     */
	TFA2_BF_IPOCFMAC= 0x4de0,	/*!< Polarity cfma ack				                     */
	TFA2_BF_IPCLKOOR= 0x4df0,	/*!< Polarity flag_clk_out_of_range				        */
	TFA2_BF_IPOTDMER= 0x4e00,	/*!< Polarity tdm error				                    */
	TFA2_BF_IPOCLPL= 0x4e10,	/*!< Polarity clip left				                    */
	TFA2_BF_IPOCLPR= 0x4e20,	/*!< Polarity clip right				                   */
	TFA2_BF_IPOOCPM= 0x4e30,	/*!< Polarity mic ocpok				                    */
	TFA2_BF_BSSCR = 0x5001,	/*!< Battery protection attack Time				        */
	TFA2_BF_BSST	= 0x5023,	/*!< Battery protection threshold voltage level		 */
	TFA2_BF_BSSRL = 0x5061,	/*!< Battery protection maximum reduction				  */
	TFA2_BF_BSSRR = 0x5082,	/*!< Battery protection release time				       */
	TFA2_BF_BSSHY = 0x50b1,	/*!< Battery protection hysteresis				         */
	TFA2_BF_BSSR	= 0x50e0,	/*!< Battery voltage read out			                */
	TFA2_BF_BSSBY = 0x50f0,	/*!< Bypass HW clipper				                     */
	TFA2_BF_BSSS	= 0x5100,	/*!< Vbat prot steepness			                     */
	TFA2_BF_INTSMUTE= 0x5110,	/*!< Soft mute HW				                          */
	TFA2_BF_CFSML = 0x5120,	/*!< Soft mute FW left				                     */
	TFA2_BF_CFSMR = 0x5130,	/*!< Soft mute FW right				                    */
	TFA2_BF_HPFBYPL= 0x5140,	/*!< Bypass HPF left				                       */
	TFA2_BF_HPFBYPR= 0x5150,	/*!< Bypass HPF right				                      */
	TFA2_BF_DPSAL = 0x5160,	/*!< Enable DPSA left				                      */
	TFA2_BF_DPSAR = 0x5170,	/*!< Enable DPSA right				                     */
	TFA2_BF_VOL	= 0x5187,	/*!< FW volume control for primary audio channel		*/
	TFA2_BF_HNDSFRCV= 0x5200,	/*!< Selection receiver				                    */
	TFA2_BF_CLIPCTRL= 0x5222,	/*!< Clip control setting				                  */
	TFA2_BF_AMPGAIN= 0x5257,	/*!< Amplifier gain				                        */
	TFA2_BF_SLOPEE= 0x52d0,	/*!< Enables slope control				                 */
	TFA2_BF_SLOPESET= 0x52e1,	/*!< Set slope				                             */
	TFA2_BF_VOLSEC= 0x5a07,	/*!< FW volume control for secondary audio channel		*/
	TFA2_BF_SWPROFIL= 0x5a87,	/*!< Software profile data				                 */
	TFA2_BF_DCVO	= 0x7002,	/*!< Boost voltage			                           */
	TFA2_BF_DCMCC = 0x7033,	/*!< Max coil current				                      */
	TFA2_BF_DCCV	= 0x7071,	/*!< Coil Value			                              */
	TFA2_BF_DCIE	= 0x7090,	/*!< Adaptive boost mode			                     */
	TFA2_BF_DCSR	= 0x70a0,	/*!< Soft ramp up/down			                       */
	TFA2_BF_DCSYNCP= 0x70b2,	/*!< DCDC synchronization off + 7 positions				*/
	TFA2_BF_DCDIS = 0x70e0,	/*!< DCDC on/off				                           */
	TFA2_BF_RST	= 0x9000,	/*!< Reset			                                    */
	TFA2_BF_DMEM	= 0x9011,	/*!< Target memory			                           */
	TFA2_BF_AIF	= 0x9030,	/*!< Auto increment			                           */
	TFA2_BF_CFINT = 0x9040,	/*!< Interrupt - auto clear				                */
	TFA2_BF_CFCGATE= 0x9050,	/*!< Coolflux clock gating disabling control			 */
	TFA2_BF_REQ	= 0x9087,	/*!< request for access (8 channels)			          */
	TFA2_BF_REQCMD= 0x9080,	/*!< Firmware event request rpc command				    */
	TFA2_BF_REQRST= 0x9090,	/*!< Firmware event request reset restart				  */
	TFA2_BF_REQMIPS= 0x90a0,	/*!< Firmware event request short on mips				  */
	TFA2_BF_REQMUTED= 0x90b0,	/*!< Firmware event request mute sequence ready		 */
	TFA2_BF_REQVOL= 0x90c0,	/*!< Firmware event request volume ready				   */
	TFA2_BF_REQDMG= 0x90d0,	/*!< Firmware event request speaker damage detected	 */
	TFA2_BF_REQCAL= 0x90e0,	/*!< Firmware event request calibration completed		*/
	TFA2_BF_REQRSV= 0x90f0,	/*!< Firmware event request reserved				       */
	TFA2_BF_MADD	= 0x910f,	/*!< Memory address			                          */
	TFA2_BF_MEMA	= 0x920f,	/*!< Activate memory access			                  */
	TFA2_BF_ERR	= 0x9307,	/*!< Error flags			                              */
	TFA2_BF_ACK	= 0x9387,	/*!< Acknowledge of requests			                  */
	TFA2_BF_ACKCMD= 0x9380,	/*!< Firmware event acknowledge rpc command				*/
	TFA2_BF_ACKRST= 0x9390,	/*!< Firmware event acknowledge reset restart			*/
	TFA2_BF_ACKMIPS= 0x93a0,	/*!< Firmware event acknowledge short on mips			*/
	TFA2_BF_ACKMUTED= 0x93b0,	/*!< Firmware event acknowledge mute sequence ready	 */
	TFA2_BF_ACKVOL= 0x93c0,	/*!< Firmware event acknowledge volume ready			 */
	TFA2_BF_ACKDMG= 0x93d0,	/*!< Firmware event acknowledge speaker damage detected */
	TFA2_BF_ACKCAL= 0x93e0,	/*!< Firmware event acknowledge calibration completed	*/
	TFA2_BF_ACKRSV= 0x93f0,	/*!< Firmware event acknowledge reserved				   */
	TFA2_BF_MTPK	= 0xa107,	/*!< MTP KEY2 register			                       */
	TFA2_BF_KEY1LOCKED= 0xa200,	/*!< Indicates KEY1 is locked				              */
	TFA2_BF_KEY2LOCKED= 0xa210,	/*!< Indicates KEY2 is locked				              */
	TFA2_BF_CIMTP = 0xa360,	/*!< Start copying data from I2C mtp registers to mtp	*/
	TFA2_BF_MTPRDMSB= 0xa50f,	/*!< MSB word of MTP manual read data				      */
	TFA2_BF_MTPRDLSB= 0xa60f,	/*!< LSB word of MTP manual read data				      */
	TFA2_BF_EXTTS = 0xb108,	/*!< External temperature (C)				              */
	TFA2_BF_TROS	= 0xb190,	/*!< Select temp Speaker calibration			         */
	TFA2_BF_MTPOTC= 0xf000,	/*!< Calibration schedule				                  */
	TFA2_BF_MTPEX = 0xf010,	/*!< Calibration Ron executed				              */
	TFA2_BF_DCMCCAPI= 0xf020,	/*!< Calibration current limit DCDC				        */
	TFA2_BF_DCMCCSB= 0xf030,	/*!< Sign bit for delta calibration current limit DCDC	*/
	TFA2_BF_USERDEF= 0xf042,	/*!< Calibration delta current limit DCDC				  */
	TFA2_BF_R25CL = 0xf40f,	/*!< Ron resistance of left channel speaker coil		*/
	TFA2_BF_R25CR = 0xf50f,	/*!< Ron resistance of right channel speaker coil		*/
};

enum tfa2_irq {
	tfa2_irq_stvdds = 0,
	tfa2_irq_stplls = 1,
	tfa2_irq_stotds = 2,
	tfa2_irq_stovds = 3,
	tfa2_irq_stuvds = 4,
	tfa2_irq_stclks = 5,
	tfa2_irq_stmtpb = 6,
	tfa2_irq_stnoclk = 7,
	tfa2_irq_stspks = 8,
	tfa2_irq_stacs = 9,
	tfa2_irq_stsws = 10,
	tfa2_irq_stwds = 11,
	tfa2_irq_stamps = 12,
	tfa2_irq_starefs = 13,
	tfa2_irq_stadccr = 14,
	tfa2_irq_stbodnok = 15,
	tfa2_irq_stbstcu = 16,
	tfa2_irq_stbsthi = 17,
	tfa2_irq_stbstoc = 18,
	tfa2_irq_stbstpkcur = 19,
	tfa2_irq_stbstvc = 20,
	tfa2_irq_stbst86 = 21,
	tfa2_irq_stbst93 = 22,
	tfa2_irq_strcvld = 23,
	tfa2_irq_stocpl = 24,
	tfa2_irq_stocpr = 25,
	tfa2_irq_stmwsrc = 26,
	tfa2_irq_stmwcfc = 27,
	tfa2_irq_stmwsmu = 28,
	tfa2_irq_stcfmer = 29,
	tfa2_irq_stcfmac = 30,
	tfa2_irq_stclkoor = 31,
	tfa2_irq_sttdmer = 32,
	tfa2_irq_stclpl = 33,
	tfa2_irq_stclpr = 34,
	tfa2_irq_stocpm = 35,
	tfa2_irq_max = 36,
	tfa2_irq_all = -1 /* all irqs */};
