[DEFAULT]
debian-branch = mobian-sdm670-6.12
debian-tag = mobian/sdm670-%(version)s
upstream-tag = upstream/%(version)s
upstream-branch = linux-6.12.y
upstream-vcs-tag = v%(version)s
pristine-tar = false

[dch]
commit-msg = d/changelog: release version %(version)s
